"""머신 카탈로그 — SETTING.MD §10.4 (v2).

(brand, model, name_ko, target_code | None)
종목에 선택적으로 연결해 "어느 기구에서 했는지"를 식별하는 용도. 연식·브랜드별 타겟 차이는
앱이 알 필요가 없다 — 타겟은 기록할 때 세트 단위로 고른다. target_code는 참고값일 뿐이다.
기동 시 (brand, model) 기준 INSERT OR IGNORE.

초안 출처: 2026-09-08 웹 조사(제조사 카탈로그·국내 딜러 페이지). 모델명은 제조사 표기, name_ko는
통용 별칭. 목록 검토·수정은 사용자 몫 — 코드가 아니라 데이터라 자유롭게 고쳐도 된다.
"""

MACHINES: list[tuple[str, str, str, str | None]] = [
    # ---- Hammer Strength ----
    ('Hammer Strength', 'Ground Base Jammer', '해머 그라운드 베이스 재머', 'chest'),
    ('Hammer Strength', 'Plate Loaded Glute Drive', '해머 글루트 드라이브', 'glutes'),
    ('Hammer Strength', 'T-Bar Row', '해머 티바 로우', 'back'),
    ('Hammer Strength', 'Iso-Lateral Bench Press', '해머 벤치 프레스', 'chest'),
    ('Hammer Strength', 'Abdominal / Oblique Crunch', '해머 복근 크런치', 'abs'),
    ('Hammer Strength', 'Plate Loaded Belt Squat', '해머 벨트 스쿼트', 'quads'),
    ('Hammer Strength', 'Ground Base Combo Twist', '해머 콤보 트위스트', 'obliques'),
    ('Hammer Strength', 'Plate Loaded Gripper', '해머 그리퍼', 'forearms'),
    ('Hammer Strength', 'Iso-Lateral Chest / Back', '해머 체스트/백 콤보', 'chest'),
    ('Hammer Strength', 'Iso-Lateral D.Y. Row', '해머 DY 로우', 'lats'),
    ('Hammer Strength', 'Iso-Lateral Decline Chest Press', '해머 디클라인 프레스', 'lower_chest'),
    ('Hammer Strength', 'Iso-Lateral Front Lat Pulldown', '해머 프론트 랫풀다운', 'lats'),
    ('Hammer Strength', 'Iso-Lateral High Row', '해머 하이 로우', 'lats'),
    ('Hammer Strength', 'Iso-Lateral Horizontal Bench Press', '해머 호리젠탈 벤치 프레스', 'mid_chest'),
    ('Hammer Strength', 'Iso-Lateral Incline Press', '해머 인클라인 프레스', 'upper_chest'),
    ('Hammer Strength', 'Iso-Lateral Kneeling Leg Curl', '해머 닐링 레그컬', 'hamstrings'),
    ('Hammer Strength', 'Iso-Lateral Leg Curl', '해머 레그컬', 'hamstrings'),
    ('Hammer Strength', 'Iso-Lateral Low Row', '해머 로우 로우', 'lats'),
    ('Hammer Strength', 'Iso-Lateral Row', '해머 로우', 'back'),
    ('Hammer Strength', 'Iso-Lateral Shoulder Press', '해머 숄더 프레스', 'shoulders'),
    ('Hammer Strength', 'Iso-Lateral Super Incline Press', '해머 슈퍼 인클라인 프레스', 'upper_chest'),
    ('Hammer Strength', 'Iso-Lateral Wide Chest', '해머 와이드 체스트', 'chest'),
    ('Hammer Strength', 'Iso-Lateral Wide Pulldown', '해머 와이드 풀다운', 'lats'),
    ('Hammer Strength', 'Plate Loaded Lateral Raise', '해머 래터럴 레이즈', 'side_delt'),
    ('Hammer Strength', 'Plate Loaded Hack Squat', '해머 핵 스쿼트', 'quads'),
    ('Hammer Strength', 'Plate Loaded Linear Leg Press', '해머 리니어 레그 프레스', 'quads'),
    ('Hammer Strength', 'Plate Loaded Pullover', '해머 풀오버', 'lats'),
    ('Hammer Strength', 'Plate Loaded Seated Biceps', '해머 시티드 바이셉스', 'biceps'),
    ('Hammer Strength', 'Ground Base Squat / High Pull', '해머 스쿼트/하이풀', 'quads'),
    ('Hammer Strength', 'Seated / Standing Shrug', '해머 슈러그', 'upper_traps'),
    ('Hammer Strength', 'Plate Loaded Seated Dip', '해머 시티드 딥', 'triceps'),
    ('Hammer Strength', 'Plate Loaded Seated Calf Raise', '해머 시티드 카프 레이즈', 'soleus'),
    ('Hammer Strength', 'Plate-Loaded Vertical Smith Machine', '해머 스미스 머신', None),
    ('Hammer Strength', 'Plate Loaded Assisted Nordic Ham', '해머 노르딕 햄', 'hamstrings'),
    ('Hammer Strength', 'Glute Ham / Reverse Hyper', '해머 GHD / 리버스 하이퍼', 'hamstrings'),
    ('Hammer Strength', 'Iso-Lateral Leg Extension', '해머 레그 익스텐션', 'quads'),
    ('Hammer Strength', 'Ground Base Multi-Squat', '해머 멀티 스쿼트', 'quads'),
    ('Hammer Strength', 'Plate Loaded Super Squat Press', '해머 슈퍼 스쿼트 프레스', 'quads'),
    ('Hammer Strength', 'Plate Loaded Pendulum-X Squat', '해머 펜듈럼 스쿼트', 'quads'),
    ('Hammer Strength', 'Plate Loaded Super Fly', '해머 슈퍼 플라이', 'chest'),
    ('Hammer Strength', 'Iso-Lateral T-Bar Row', '해머 아이소 티바 로우', 'back'),
    ('Hammer Strength', 'Plate Loaded Reverse V-Squat', '해머 리버스 V 스쿼트', 'quads'),
    ('Hammer Strength', 'Select Assist Dip Chin', '해머 셀렉트 어시스트 딥/친', 'lats'),
    ('Hammer Strength', 'Select Biceps Curl', '해머 셀렉트 바이셉스 컬', 'biceps'),
    ('Hammer Strength', 'Select Chest Press', '해머 셀렉트 체스트 프레스', 'chest'),
    ('Hammer Strength', 'Select Fixed Pulldown', '해머 셀렉트 픽스드 풀다운', 'lats'),
    ('Hammer Strength', 'Select Lat Pulldown', '해머 셀렉트 랫풀다운', 'lats'),
    ('Hammer Strength', 'Select Lateral Raise', '해머 셀렉트 래터럴 레이즈', 'side_delt'),
    ('Hammer Strength', 'Select Seated Row', '해머 셀렉트 시티드 로우', 'back'),
    ('Hammer Strength', 'Select Shoulder Press', '해머 셀렉트 숄더 프레스', 'shoulders'),
    ('Hammer Strength', 'Select Pectoral Fly/Rear Deltoid', '해머 셀렉트 펙 플라이/리어 델트', 'chest'),
    ('Hammer Strength', 'Select Triceps Extension', '해머 셀렉트 트라이셉스 익스텐션', 'triceps'),
    ('Hammer Strength', 'Select Pectoral Fly', '해머 셀렉트 펙 플라이', 'chest'),
    ('Hammer Strength', 'Select Abdominal Crunch', '해머 셀렉트 복근 크런치', 'abs'),
    ('Hammer Strength', 'Select Back Extension', '해머 셀렉트 백 익스텐션', 'lower_back'),
    ('Hammer Strength', 'Select Hip Abduction', '해머 셀렉트 힙 어브덕션', 'glute_med'),
    ('Hammer Strength', 'Select Hip Adduction', '해머 셀렉트 힙 어덕션', 'adductors'),
    ('Hammer Strength', 'Select Hip and Glute', '해머 셀렉트 힙 앤 글루트', 'glutes'),
    ('Hammer Strength', 'Select Horizontal Calf', '해머 셀렉트 호리젠탈 카프', 'calves'),
    ('Hammer Strength', 'Select Leg Curl', '해머 셀렉트 레그컬', 'hamstrings'),
    ('Hammer Strength', 'Select Leg Extension', '해머 셀렉트 레그 익스텐션', 'quads'),
    ('Hammer Strength', 'Select Seated Leg Press', '해머 셀렉트 시티드 레그 프레스', 'quads'),
    ('Hammer Strength', 'Select Standing Calf', '해머 셀렉트 스탠딩 카프', 'gastrocnemius'),
    ('Hammer Strength', 'Select Seated Leg Curl', '해머 셀렉트 시티드 레그컬', 'hamstrings'),
    ('Hammer Strength', 'MTS Abdominal Crunch', '해머 MTS 복근 크런치', 'abs'),
    ('Hammer Strength', 'MTS Iso-Lateral Biceps Curl', '해머 MTS 바이셉스 컬', 'biceps'),
    ('Hammer Strength', 'MTS Iso-Lateral Chest Press', '해머 MTS 체스트 프레스', 'chest'),
    ('Hammer Strength', 'MTS Iso-Lateral Decline Press', '해머 MTS 디클라인 프레스', 'lower_chest'),
    ('Hammer Strength', 'MTS Iso-Lateral Front Pulldown', '해머 MTS 프론트 풀다운', 'lats'),
    ('Hammer Strength', 'MTS Iso-Lateral High Row', '해머 MTS 하이 로우', 'lats'),
    ('Hammer Strength', 'MTS Iso-Lateral Incline Press', '해머 MTS 인클라인 프레스', 'upper_chest'),
    ('Hammer Strength', 'MTS Iso-Lateral Row', '해머 MTS 로우', 'back'),
    ('Hammer Strength', 'MTS Iso-Lateral Shoulder Press', '해머 MTS 숄더 프레스', 'shoulders'),
    ('Hammer Strength', 'MTS Iso-Lateral Triceps Extension', '해머 MTS 트라이셉스 익스텐션', 'triceps'),
    ('Hammer Strength', 'MTS Iso-Lateral Leg Extension', '해머 MTS 레그 익스텐션', 'quads'),
    ('Hammer Strength', 'MTS Iso-Lateral Kneeling Leg Curl', '해머 MTS 닐링 레그컬', 'hamstrings'),
    ('Hammer Strength', 'HD Elite iD Combo Rack', '해머 HD 엘리트 콤보 랙', None),
    ('Hammer Strength', 'HD Elite iD Half Rack', '해머 HD 엘리트 하프 랙', None),
    ('Hammer Strength', 'HD Elite iD Power Rack', '해머 HD 엘리트 파워 랙', None),
    ('Hammer Strength', 'HD Elite Half Rack', '해머 HD 엘리트 하프 랙 (구형)', None),
    ('Hammer Strength', 'HD Elite Power Rack', '해머 HD 엘리트 파워 랙 (구형)', None),
    # ---- Life Fitness ----
    ('Life Fitness', 'Insignia Series Dual Axis Chest Press', '라이프 인시그니아 듀얼 액시스 체스트 프레스', 'chest'),
    ('Life Fitness', 'Insignia Series Assist Dip Chin', '라이프 인시그니아 어시스트 딥/친', 'lats'),
    ('Life Fitness', 'Insignia Series Biceps Curl', '라이프 인시그니아 바이셉스 컬', 'biceps'),
    ('Life Fitness', 'Insignia Series Biceps Curl - Dependent', '라이프 인시그니아 바이셉스 컬 (디펜던트)', 'biceps'),
    ('Life Fitness', 'Insignia Series Chest Press', '라이프 인시그니아 체스트 프레스', 'chest'),
    ('Life Fitness', 'Insignia Series Dual Axis Pulldown', '라이프 인시그니아 듀얼 액시스 풀다운', 'lats'),
    ('Life Fitness', 'Insignia Series Lateral Raise', '라이프 인시그니아 래터럴 레이즈', 'side_delt'),
    ('Life Fitness', 'Insignia Series Pectoral Fly/Rear Deltoid', '라이프 인시그니아 펙 플라이/리어 델트', 'chest'),
    ('Life Fitness', 'Insignia Series Pulldown', '라이프 인시그니아 풀다운', 'lats'),
    ('Life Fitness', 'Insignia Series Row', '라이프 인시그니아 로우', 'back'),
    ('Life Fitness', 'Insignia Series Shoulder Press', '라이프 인시그니아 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Insignia Series Triceps Extension', '라이프 인시그니아 트라이셉스 익스텐션', 'triceps'),
    ('Life Fitness', 'Insignia Series Triceps Press', '라이프 인시그니아 트라이셉스 프레스', 'triceps'),
    ('Life Fitness', 'Insignia Series Abdominal', '라이프 인시그니아 업도미널', 'abs'),
    ('Life Fitness', 'Insignia Series Torso Rotation', '라이프 인시그니아 토르소 로테이션', 'obliques'),
    ('Life Fitness', 'Insignia Series Abdominal Advanced', '라이프 인시그니아 업도미널 어드밴스드', 'abs'),
    ('Life Fitness', 'Insignia Series Back Extension', '라이프 인시그니아 백 익스텐션', 'lower_back'),
    ('Life Fitness', 'Insignia Series Arc Leg Press', '라이프 인시그니아 아크 레그 프레스', 'quads'),
    ('Life Fitness', 'Insignia Series Calf Extension', '라이프 인시그니아 카프 익스텐션', 'calves'),
    ('Life Fitness', 'Insignia Series Glute', '라이프 인시그니아 글루트', 'glutes'),
    ('Life Fitness', 'Insignia Series Glute Bridge', '라이프 인시그니아 글루트 브릿지', 'glutes'),
    ('Life Fitness', 'Insignia Series Hip Abduction / Adduction', '라이프 인시그니아 힙 어브덕션/어덕션', 'glute_med'),
    ('Life Fitness', 'Insignia Series Hip Adduction', '라이프 인시그니아 힙 어덕션', 'adductors'),
    ('Life Fitness', 'Insignia Series Leg Curl', '라이프 인시그니아 레그컬', 'hamstrings'),
    ('Life Fitness', 'Insignia Series Leg Extension', '라이프 인시그니아 레그 익스텐션', 'quads'),
    ('Life Fitness', 'Insignia Series Seated Leg Curl', '라이프 인시그니아 시티드 레그컬', 'hamstrings'),
    ('Life Fitness', 'Insignia Series Sit / Stand Hip Abductor', '라이프 인시그니아 힙 어브덕터', 'glute_med'),
    ('Life Fitness', 'Plate Loaded Calf Raise', '라이프 플레이트 카프 레이즈', 'calves'),
    ('Life Fitness', 'Plate Loaded Decline Chest Press', '라이프 플레이트 디클라인 체스트 프레스', 'lower_chest'),
    ('Life Fitness', 'Plate Loaded Seated Dip', '라이프 플레이트 시티드 딥', 'triceps'),
    ('Life Fitness', 'Plate Loaded Pulldown', '라이프 플레이트 풀다운', 'lats'),
    ('Life Fitness', 'Plate Loaded High Row', '라이프 플레이트 하이 로우', 'lats'),
    ('Life Fitness', 'Plate Loaded Kneeling Leg Curl', '라이프 플레이트 닐링 레그컬', 'hamstrings'),
    ('Life Fitness', 'Plate Loaded Leg Extension', '라이프 플레이트 레그 익스텐션', 'quads'),
    ('Life Fitness', 'Plate Loaded Linear Leg Press', '라이프 플레이트 리니어 레그 프레스', 'quads'),
    ('Life Fitness', 'Plate Loaded Incline Press', '라이프 플레이트 인클라인 프레스', 'upper_chest'),
    ('Life Fitness', 'Plate Loaded Row', '라이프 플레이트 로우', 'back'),
    ('Life Fitness', 'Plate Loaded Shoulder Press', '라이프 플레이트 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Plate Loaded Biceps Curl', '라이프 플레이트 바이셉스 컬', 'biceps'),
    ('Life Fitness', 'Smith Machine', '라이프 스미스 머신', None),
    ('Life Fitness', 'Signature Series Chest Press', '라이프 시그니처 체스트 프레스', 'chest'),
    ('Life Fitness', 'Signature Series Shoulder Press', '라이프 시그니처 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Signature Series Pectoral Fly', '라이프 시그니처 펙 플라이', 'chest'),
    ('Life Fitness', 'Signature Series Triceps Press / Seated Dip', '라이프 시그니처 트라이셉스 프레스', 'triceps'),
    ('Life Fitness', 'Signature Series Leg Press', '라이프 시그니처 레그 프레스', 'quads'),
    ('Life Fitness', 'Signature Series Leg Extension', '라이프 시그니처 레그 익스텐션', 'quads'),
    ('Life Fitness', 'Signature Series Leg Curl', '라이프 시그니처 레그컬', 'hamstrings'),
    ('Life Fitness', 'Signature Series Cable Motion Chest Press', '라이프 시그니처 케이블 모션 체스트 프레스', 'chest'),
    ('Life Fitness', 'Signature Series Cable Motion Shoulder Press', '라이프 시그니처 케이블 모션 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Signature Series Plate Loaded Shoulder Press', '라이프 시그니처 플레이트 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Optima Series Chest Press', '라이프 옵티마 체스트 프레스', 'chest'),
    ('Life Fitness', 'Optima Series Leg Curl', '라이프 옵티마 레그컬', 'hamstrings'),
    ('Life Fitness', 'Optima Series Leg Extension', '라이프 옵티마 레그 익스텐션', 'quads'),
    ('Life Fitness', 'Optima Series Seated Leg Press', '라이프 옵티마 시티드 레그 프레스', 'quads'),
    ('Life Fitness', 'Optima Series Lat Pulldown / Low Row', '라이프 옵티마 랫풀다운/로우 로우', 'lats'),
    ('Life Fitness', 'Optima Series Leg Extension / Leg Curl Combo', '라이프 옵티마 레그 익스텐션/레그컬 콤보', 'quads'),
    ('Life Fitness', 'Optima Series Multi-Press', '라이프 옵티마 멀티 프레스', 'chest'),
    ('Life Fitness', 'Optima Series Biceps Curl', '라이프 옵티마 바이셉스 컬', 'biceps'),
    ('Life Fitness', 'Optima Series Shoulder Press', '라이프 옵티마 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Optima Series Pec Fly / Rear Delt', '라이프 옵티마 펙 플라이/리어 델트', 'chest'),
    ('Life Fitness', 'Optima Series Seated Row', '라이프 옵티마 시티드 로우', 'back'),
    ('Life Fitness', 'Circuit Series Chest Press', '라이프 서킷 체스트 프레스', 'chest'),
    ('Life Fitness', 'Circuit Series Shoulder Press', '라이프 서킷 숄더 프레스', 'shoulders'),
    ('Life Fitness', 'Circuit Series Leg Extension', '라이프 서킷 레그 익스텐션', 'quads'),
    ('Life Fitness', 'Circuit Series Triceps Press', '라이프 서킷 트라이셉스 프레스', 'triceps'),
    ('Life Fitness', 'Circuit Series Seated Leg Curl', '라이프 서킷 시티드 레그컬', 'hamstrings'),
    ('Life Fitness', 'Circuit Series Seated Row', '라이프 서킷 시티드 로우', 'back'),
    ('Life Fitness', 'Circuit Series Lat Pulldown', '라이프 서킷 랫풀다운', 'lats'),
    ('Life Fitness', 'Circuit Series Biceps Curl', '라이프 서킷 바이셉스 컬', 'biceps'),
    ('Life Fitness', 'Circuit Series Squat', '라이프 서킷 스쿼트', 'quads'),
    # ---- gym80 ----
    ('gym80', 'Leg Extension', 'gym80 레그 익스텐션', 'quads'),
    ('gym80', 'Lying Leg Curl', 'gym80 라잉 레그컬', 'hamstrings'),
    ('gym80', 'Seated Leg Curl', 'gym80 시티드 레그컬', 'hamstrings'),
    ('gym80', 'Kneeling Glutes Kick', 'gym80 닐링 글루트 킥', 'glutes'),
    ('gym80', 'Gluteus Kick Radial', 'gym80 글루트 킥 래디얼', 'glutes'),
    ('gym80', 'Total Hip Machine', 'gym80 토탈 힙', 'glutes'),
    ('gym80', 'Lower Back Machine (3007)', 'gym80 로어 백 머신', 'lower_back'),
    ('gym80', 'Abdominal Crunch', 'gym80 복근 크런치', 'abs'),
    ('gym80', 'Biceps Machine', 'gym80 바이셉스 머신', 'biceps'),
    ('gym80', 'Triceps Extension', 'gym80 트라이셉스 익스텐션', 'triceps'),
    ('gym80', 'Pull Over Machine', 'gym80 풀오버', 'lats'),
    ('gym80', 'Standing Leg Curl', 'gym80 스탠딩 레그컬', 'hamstrings'),
    ('gym80', 'Chest Crossover Machine', 'gym80 체스트 크로스오버', 'chest'),
    ('gym80', 'Seated Chest Press', 'gym80 시티드 체스트 프레스', 'chest'),
    ('gym80', 'Kneeling / Chinning-Dipping Machine', 'gym80 어시스트 친/딥', 'lats'),
    ('gym80', 'Standing Calf Raise Machine', 'gym80 스탠딩 카프 레이즈', 'gastrocnemius'),
    ('gym80', 'Lat Pulldown Machine', 'gym80 랫풀다운', 'lats'),
    ('gym80', 'Butterfly with Pads', 'gym80 버터플라이 (패드형)', 'chest'),
    ('gym80', 'Butterfly', 'gym80 버터플라이', 'chest'),
    ('gym80', 'Incline Chest Press', 'gym80 인클라인 체스트 프레스', 'upper_chest'),
    ('gym80', 'Butterfly Reverse', 'gym80 리버스 버터플라이', 'rear_delt'),
    ('gym80', 'Seated Calf Press', 'gym80 시티드 카프 프레스', 'soleus'),
    ('gym80', 'Abduction Machine', 'gym80 어브덕션', 'glute_med'),
    ('gym80', 'Adduction Machine', 'gym80 어덕션', 'adductors'),
    ('gym80', 'Seated Leg Press', 'gym80 시티드 레그 프레스', 'quads'),
    ('gym80', 'Lying Leg Press', 'gym80 라잉 레그 프레스', 'quads'),
    ('gym80', 'Shoulder Press', 'gym80 숄더 프레스', 'shoulders'),
    ('gym80', 'Lying Abdominal Machine', 'gym80 라잉 업도미널', 'abs'),
    ('gym80', 'Dip Machine', 'gym80 딥 머신', 'triceps'),
    ('gym80', 'Abdominal Machine', 'gym80 업도미널 머신', 'abs'),
    ('gym80', 'Lower Back Machine (3038)', 'gym80 로어 백 머신 (3038)', 'lower_back'),
    ('gym80', 'Seated Row Without Chest Support', 'gym80 시티드 로우 (체스트 서포트 없음)', 'back'),
    ('gym80', 'Seated Row Machine', 'gym80 시티드 로우', 'back'),
    ('gym80', 'Dual Chest Press', 'gym80 듀얼 체스트 프레스', 'chest'),
    ('gym80', 'Dual Incline Chest Press', 'gym80 듀얼 인클라인 체스트 프레스', 'upper_chest'),
    ('gym80', 'Dual Shoulder Press', 'gym80 듀얼 숄더 프레스', 'shoulders'),
    ('gym80', 'Dual Lat Pulldown', 'gym80 듀얼 랫풀다운', 'lats'),
    ('gym80', 'Dual Seated Row', 'gym80 듀얼 시티드 로우', 'back'),
    ('gym80', 'Dual Leg Press', 'gym80 듀얼 레그 프레스', 'quads'),
    ('gym80', 'ISO Lat', 'gym80 아이소 랫', 'lats'),
    ('gym80', 'Shoulder Lateral Raise with Grips', 'gym80 래터럴 레이즈 (그립형)', 'side_delt'),
    ('gym80', 'Standing Abduction', 'gym80 스탠딩 어브덕션', 'glute_med'),
    ('gym80', 'Forearms Machine', 'gym80 포암 머신', 'forearms'),
    ('gym80', 'Donkey Calf', 'gym80 동키 카프', 'gastrocnemius'),
    ('gym80', 'Triceps Overhead', 'gym80 트라이셉스 오버헤드', 'triceps'),
    ('gym80', 'Neck Press', 'gym80 넥 프레스', 'shoulders'),
    ('gym80', 'Inner Chest Press', 'gym80 이너 체스트 프레스', 'mid_chest'),
    ('gym80', 'Horizontal Biceps', 'gym80 호리젠탈 바이셉스', 'biceps'),
    ('gym80', 'Standing Shoulder Lateral Raise', 'gym80 스탠딩 래터럴 레이즈', 'side_delt'),
    ('gym80', 'Standing Chest Crossover Machine', 'gym80 스탠딩 체스트 크로스오버', 'chest'),
    ('gym80', 'Lying Leg Extension with Adjustable Backrest', 'gym80 라잉 레그 익스텐션', 'quads'),
    ('gym80', 'Crunch Machine', 'gym80 크런치 머신', 'abs'),
    ('gym80', 'Rotary Machine', 'gym80 로터리 머신', 'obliques'),
    ('gym80', 'Cable Crossover Station', 'gym80 케이블 크로스오버', 'chest'),
    ('gym80', 'Rowing Station', 'gym80 로잉 스테이션', 'back'),
    ('gym80', 'Dual Adjustable Pulley', 'gym80 듀얼 어저스터블 풀리', None),
    ('gym80', 'Pure Kraft T-Bar Row', 'gym80 퓨어크래프트 티바 로우', 'back'),
    ('gym80', 'Pure Kraft 45 Degrees Linear Leg Press', 'gym80 퓨어크래프트 45도 레그 프레스', 'quads'),
    ('gym80', 'Pure Kraft Seated Calf Raise', 'gym80 퓨어크래프트 시티드 카프 레이즈', 'soleus'),
    ('gym80', 'Pure Kraft Squat Machine', 'gym80 퓨어크래프트 스쿼트 머신', 'quads'),
    ('gym80', 'Pure Kraft Hack Squat', 'gym80 퓨어크래프트 핵 스쿼트', 'quads'),
    ('gym80', 'Pure Kraft Lying Abdominal', 'gym80 퓨어크래프트 라잉 업도미널', 'abs'),
    ('gym80', 'Pure Kraft Lat Pulldown Dual', 'gym80 퓨어크래프트 랫풀다운', 'lats'),
    ('gym80', 'Pure Kraft Seated Leg Press Dual', 'gym80 퓨어크래프트 시티드 레그 프레스', 'quads'),
    ('gym80', 'Pure Kraft Ab Swing', 'gym80 퓨어크래프트 앱 스윙', 'abs'),
    ('gym80', 'Pure Kraft Bent Over Row', 'gym80 퓨어크래프트 벤트오버 로우', 'back'),
    ('gym80', 'Pure Kraft Low Row Dual', 'gym80 퓨어크래프트 로우 로우', 'lats'),
    ('gym80', 'Pure Kraft Shoulder Press Dual', 'gym80 퓨어크래프트 숄더 프레스', 'shoulders'),
    ('gym80', 'Pure Kraft Gluteus Kick Machine', 'gym80 퓨어크래프트 글루트 킥', 'glutes'),
    ('gym80', 'Pure Kraft Seated Row Dual', 'gym80 퓨어크래프트 시티드 로우', 'back'),
    ('gym80', 'Pure Kraft 45 Degrees Pivot Leg Press', 'gym80 퓨어크래프트 피벗 레그 프레스', 'quads'),
    ('gym80', 'Pure Kraft Standing Leg Extension', 'gym80 퓨어크래프트 스탠딩 레그 익스텐션', 'quads'),
    ('gym80', 'Pure Kraft Butterfly 50°', 'gym80 퓨어크래프트 버터플라이 50도', 'chest'),
    ('gym80', 'Biceps Machine Hybrid', 'gym80 하이브리드 바이셉스', 'biceps'),
    ('gym80', 'Leg Extension Hybrid', 'gym80 하이브리드 레그 익스텐션', 'quads'),
    ('gym80', 'Chest Press Hybrid', 'gym80 하이브리드 체스트 프레스', 'chest'),
    # ---- Nautilus ----
    ('Nautilus', 'Inspiration Leg Press', '노틸러스 인스피레이션 레그 프레스', 'quads'),
    ('Nautilus', 'Inspiration Leg Extension', '노틸러스 인스피레이션 레그 익스텐션', 'quads'),
    ('Nautilus', 'Inspiration Leg Curl', '노틸러스 인스피레이션 레그컬', 'hamstrings'),
    ('Nautilus', 'Inspiration Abduction/Adduction', '노틸러스 인스피레이션 어브덕션/어덕션', 'glute_med'),
    ('Nautilus', 'Inspiration Glute Press', '노틸러스 인스피레이션 글루트 프레스', 'glutes'),
    ('Nautilus', 'Inspiration Chest Press', '노틸러스 인스피레이션 체스트 프레스', 'chest'),
    ('Nautilus', 'Inspiration Lat Pull Down', '노틸러스 인스피레이션 랫풀다운', 'lats'),
    ('Nautilus', 'Inspiration Vertical Row', '노틸러스 인스피레이션 버티컬 로우', 'back'),
    ('Nautilus', 'Inspiration Pec Fly/Rear Deltoid', '노틸러스 인스피레이션 펙 플라이/리어 델트', 'chest'),
    ('Nautilus', 'Inspiration Shoulder Press', '노틸러스 인스피레이션 숄더 프레스', 'shoulders'),
    ('Nautilus', 'Inspiration Deltoid Raise', '노틸러스 인스피레이션 델토이드 레이즈', 'side_delt'),
    ('Nautilus', 'Inspiration Biceps Curl', '노틸러스 인스피레이션 바이셉스 컬', 'biceps'),
    ('Nautilus', 'Inspiration Bilateral Arm Curl', '노틸러스 인스피레이션 암 컬', 'biceps'),
    ('Nautilus', 'Inspiration Tricep Dip', '노틸러스 인스피레이션 트라이셉 딥', 'triceps'),
    ('Nautilus', 'Inspiration Triceps Extension', '노틸러스 인스피레이션 트라이셉스 익스텐션', 'triceps'),
    ('Nautilus', 'Inspiration Abdominal Crunch', '노틸러스 인스피레이션 복근 크런치', 'abs'),
    ('Nautilus', 'Impact Seated Leg Press', '노틸러스 임팩트 시티드 레그 프레스', 'quads'),
    ('Nautilus', 'Impact Leg Extension', '노틸러스 임팩트 레그 익스텐션', 'quads'),
    ('Nautilus', 'Impact Seated Leg Curl', '노틸러스 임팩트 시티드 레그컬', 'hamstrings'),
    ('Nautilus', 'Impact Leg Curl', '노틸러스 임팩트 레그컬', 'hamstrings'),
    ('Nautilus', 'Impact Kneeling Leg Curl', '노틸러스 임팩트 닐링 레그컬', 'hamstrings'),
    ('Nautilus', 'Impact Adductor', '노틸러스 임팩트 어덕터', 'adductors'),
    ('Nautilus', 'Impact Abductor', '노틸러스 임팩트 어브덕터', 'glute_med'),
    ('Nautilus', 'Impact Standing Calf', '노틸러스 임팩트 스탠딩 카프', 'gastrocnemius'),
    ('Nautilus', 'Impact Chest Press', '노틸러스 임팩트 체스트 프레스', 'chest'),
    ('Nautilus', 'Impact Incline Press', '노틸러스 임팩트 인클라인 프레스', 'upper_chest'),
    ('Nautilus', 'Impact Deltoid Fly', '노틸러스 임팩트 델토이드 플라이', 'rear_delt'),
    ('Nautilus', 'Impact Fixed Lat Pull Down', '노틸러스 임팩트 픽스드 랫풀다운', 'lats'),
    ('Nautilus', 'Impact Lat Pull Down', '노틸러스 임팩트 랫풀다운', 'lats'),
    ('Nautilus', 'Impact Vertical Row', '노틸러스 임팩트 버티컬 로우', 'back'),
    ('Nautilus', 'Impact Low Row', '노틸러스 임팩트 로우 로우', 'lats'),
    ('Nautilus', 'Impact Shoulder Press', '노틸러스 임팩트 숄더 프레스', 'shoulders'),
    ('Nautilus', 'Leverage Chest Press', '노틸러스 레버리지 체스트 프레스', 'chest'),
    ('Nautilus', 'Leverage Incline Press', '노틸러스 레버리지 인클라인 프레스', 'upper_chest'),
    ('Nautilus', 'Leverage Decline Press', '노틸러스 레버리지 디클라인 프레스', 'lower_chest'),
    ('Nautilus', 'Leverage Lat Pull Down', '노틸러스 레버리지 랫풀다운', 'lats'),
    ('Nautilus', 'Leverage High Row', '노틸러스 레버리지 하이 로우', 'lats'),
    ('Nautilus', 'Leverage Low Row', '노틸러스 레버리지 로우 로우', 'lats'),
    ('Nautilus', 'Leverage Shoulder Press', '노틸러스 레버리지 숄더 프레스', 'shoulders'),
    ('Nautilus', 'Leverage Biceps Curl', '노틸러스 레버리지 바이셉스 컬', 'biceps'),
    ('Nautilus', 'Leverage Abdominal Crunch', '노틸러스 레버리지 복근 크런치', 'abs'),
    ('Nautilus', 'Leverage Deadlift Shrug', '노틸러스 레버리지 데드리프트/슈러그', 'upper_traps'),
    ('Nautilus', 'Angled Leg Press', '노틸러스 앵글드 레그 프레스', 'quads'),
    ('Nautilus', 'Standing Calf', '노틸러스 스탠딩 카프', 'gastrocnemius'),
    ('Nautilus', 'Tilt Seat Calf', '노틸러스 틸트 시티드 카프', 'soleus'),
    ('Nautilus', 'Hack Squat', '노틸러스 핵 스쿼트', 'quads'),
    ('Nautilus', 'Glute Drive', '노틸러스 글루트 드라이브', 'glutes'),
    ('Nautilus', 'Freedom Rack', '노틸러스 프리덤 랙', None),
    ('Nautilus', 'Nitro Chest Press', '노틸러스 나이트로 체스트 프레스', 'chest'),
    ('Nautilus', 'Nitro Overhead Press', '노틸러스 나이트로 오버헤드 프레스', 'shoulders'),
    ('Nautilus', 'Nitro Arm Curl', '노틸러스 나이트로 암 컬', 'biceps'),
    ('Nautilus', 'Nitro Arm Extension', '노틸러스 나이트로 암 익스텐션', 'triceps'),
    ('Nautilus', 'Nitro Lat Pulldown', '노틸러스 나이트로 랫풀다운', 'lats'),
    ('Nautilus', 'Nitro Compound Row', '노틸러스 나이트로 컴파운드 로우', 'back'),
    ('Nautilus', 'Nitro Abdominal Crunch', '노틸러스 나이트로 복근 크런치', 'abs'),
    ('Nautilus', 'Nitro Abductor/Adductor Combo', '노틸러스 나이트로 어브덕터/어덕터', 'glute_med'),
    ('Nautilus', 'Nitro Gravitron Weight Assisted Chin Dip', '노틸러스 나이트로 그라비트론', 'lats'),
    ('Nautilus', 'Nitro Seated Leg Curl', '노틸러스 나이트로 시티드 레그컬', 'hamstrings'),
    ('Nautilus', 'Nitro Leg Extension', '노틸러스 나이트로 레그 익스텐션', 'quads'),
    ('Nautilus', 'Nitro Seated Leg Press', '노틸러스 나이트로 시티드 레그 프레스', 'quads'),
    ('Nautilus', 'Nitro Plus Lower Back', '노틸러스 나이트로 플러스 로어 백', 'lower_back'),
    # ---- Arsenal Strength ----
    ('Arsenal Strength', 'Reloaded Incline Fly', '아스날 인클라인 플라이', 'upper_chest'),
    ('Arsenal Strength', 'Reloaded Pendulum Squat', '아스날 펜듈럼 스쿼트', 'quads'),
    ('Arsenal Strength', 'Reloaded Lever Row', '아스날 레버 로우', 'back'),
    ('Arsenal Strength', 'Reloaded Glute Bridge', '아스날 글루트 브릿지', 'glutes'),
    ('Arsenal Strength', 'Reloaded ISO Multi Row', '아스날 아이소 멀티 로우', 'back'),
    ('Arsenal Strength', 'Reloaded ISO Shoulder Press', '아스날 아이소 숄더 프레스', 'shoulders'),
    ('Arsenal Strength', 'Reloaded Linear Leg Press', '아스날 리니어 레그 프레스', 'quads'),
    ('Arsenal Strength', 'Reloaded Standing Chest Press', '아스날 스탠딩 체스트 프레스', 'chest'),
    ('Arsenal Strength', 'Reloaded Linear Hack Squat', '아스날 리니어 핵 스쿼트', 'quads'),
    ('Arsenal Strength', 'Reloaded ISO Incline Press', '아스날 아이소 인클라인 프레스', 'upper_chest'),
    ('Arsenal Strength', 'Reloaded Tricep Kickback/Dip', '아스날 트라이셉 킥백/딥', 'triceps'),
    ('Arsenal Strength', 'Reloaded Multi Flex', '아스날 멀티 플렉스', None),
    ('Arsenal Strength', 'Reloaded Leg Extension/Seated Leg Curl', '아스날 레그 익스텐션/레그컬 콤보', 'quads'),
    ('Arsenal Strength', 'Reloaded Viking Press', '아스날 바이킹 프레스', 'shoulders'),
    ('Arsenal Strength', 'Reloaded Vertical Row', '아스날 버티컬 로우', 'back'),
    ('Arsenal Strength', 'Reloaded Seated Calf Raise', '아스날 시티드 카프 레이즈', 'soleus'),
    ('Arsenal Strength', 'Reloaded Power Squat', '아스날 파워 스쿼트', 'quads'),
    ('Arsenal Strength', 'Reloaded Bilateral Leg Press', '아스날 바이래터럴 레그 프레스', 'quads'),
    ('Arsenal Strength', 'Reloaded ISO Flat Press', '아스날 아이소 플랫 프레스', 'mid_chest'),
    ('Arsenal Strength', 'Reloaded T Bar Row', '아스날 티바 로우', 'back'),
    ('Arsenal Strength', 'Reloaded Belt Squat', '아스날 벨트 스쿼트', 'quads'),
    ('Arsenal Strength', 'Reloaded Vertical Chest Press', '아스날 버티컬 체스트 프레스', 'chest'),
    ('Arsenal Strength', 'Reloaded Vertical Leg Press', '아스날 버티컬 레그 프레스', 'quads'),
    ('Arsenal Strength', 'Reloaded Linear Smith Row', '아스날 리니어 스미스 로우', 'back'),
    ('Arsenal Strength', 'Reloaded Multi Row', '아스날 멀티 로우', 'back'),
    ('Arsenal Strength', 'Reloaded ISO Lat Pulldown', '아스날 아이소 랫풀다운', 'lats'),
    ('Arsenal Strength', 'Alpha Sissy Squat Stand', '아스날 시시 스쿼트', 'quads'),
    ('Arsenal Strength', 'Alpha 45 Degree Back Extension', '아스날 45도 백 익스텐션', 'lower_back'),
    ('Arsenal Strength', 'Alpha Smith Machine (0 or 7 Degree)', '아스날 스미스 머신', None),
    ('Arsenal Strength', 'Alpha Pro Bent Row Bench', '아스날 벤트 로우 벤치', 'back'),
    ('Arsenal Strength', 'Alpha Olympic Flat Bench', '아스날 올림픽 플랫 벤치', 'chest'),
    ('Arsenal Strength', 'Alpha Olympic Incline Bench', '아스날 올림픽 인클라인 벤치', 'upper_chest'),
    ('Arsenal Strength', 'Alpha Competition Flat Bench', '아스날 컴피티션 플랫 벤치', 'chest'),
    ('Arsenal Strength', 'Alpha Standing Preacher Curl Bench', '아스날 프리처 컬 벤치', 'biceps'),
    ('Arsenal Strength', 'Alpha Adjustable Decline Bench', '아스날 디클라인 벤치', 'abs'),
    ('Arsenal Strength', 'Alpha Multi Adjustable Bench', '아스날 멀티 어저스터블 벤치', None),
    ('Arsenal Strength', 'Alpha Adjustable Lumbar Bench', '아스날 럼바 벤치', None),
    ('Arsenal Strength', 'Alpha Upright Utility Bench', '아스날 업라이트 벤치', None),
    ('Arsenal Strength', 'Alpha Flat Bench', '아스날 플랫 벤치', None),
    ('Arsenal Strength', 'Alpha-11 Half Rack', '아스날 알파-11 하프 랙', None),
    ('Arsenal Strength', 'Alpha-11 Power Rack', '아스날 알파-11 파워 랙', None),
    ('Arsenal Strength', 'Alpha-7 Half Rack', '아스날 알파-7 하프 랙', None),
    ('Arsenal Strength', 'Alpha-7 Power Rack', '아스날 알파-7 파워 랙', None),
    # ---- 뉴텍 ----
    ('뉴텍', 'Torque Lavers Hyper (Reverse Hyper)', '뉴텍 리버스 하이퍼', 'glutes'),
    ('뉴텍', 'Torque Wide Chest Press', '뉴텍 와이드 체스트 프레스', 'chest'),
    ('뉴텍', 'Torque Hip Thrust', '뉴텍 힙 쓰러스트', 'glutes'),
    ('뉴텍', 'Torque Power Leg Press', '뉴텍 파워 레그 프레스', 'quads'),
    ('뉴텍', 'Torque V-Squat', '뉴텍 V 스쿼트', 'quads'),
    ('뉴텍', 'Torque Wide Pulldown (Rear)', '뉴텍 와이드 풀다운 (리어)', 'lats'),
    ('뉴텍', 'Torque Wide Pulldown (Front)', '뉴텍 와이드 풀다운 (프론트)', 'lats'),
    ('뉴텍', 'Torque Shoulder Press', '뉴텍 토크 숄더 프레스', 'shoulders'),
    ('뉴텍', 'Torque Leg Extension', '뉴텍 토크 레그 익스텐션', 'quads'),
    ('뉴텍', 'Torque Kneeling Leg Curl', '뉴텍 닐링 레그컬', 'hamstrings'),
    ('뉴텍', 'Torque Chest & Decline Combo', '뉴텍 체스트/디클라인 콤보', 'chest'),
    ('뉴텍', 'Torque Incline Chest Press', '뉴텍 토크 인클라인 체스트 프레스', 'upper_chest'),
    ('뉴텍', 'Torque Low Row', '뉴텍 토크 로우 로우', 'lats'),
    ('뉴텍', 'Torque Front Row', '뉴텍 토크 프론트 로우', 'back'),
    ('뉴텍', 'Torque Seated Row', '뉴텍 토크 시티드 로우', 'back'),
    ('뉴텍', 'Seated Leg Press (NT-01L)', '뉴텍 시티드 레그 프레스', 'quads'),
    ('뉴텍', 'Leg Extension (NT-02L)', '뉴텍 레그 익스텐션', 'quads'),
    ('뉴텍', 'Leg Curl Machine (NT-03L)', '뉴텍 레그컬', 'hamstrings'),
    ('뉴텍', 'Inner Thigh Machine (NT-04L)', '뉴텍 이너 타이', 'adductors'),
    ('뉴텍', 'Standing Calf Machine (NT-06L)', '뉴텍 스탠딩 카프', 'gastrocnemius'),
    ('뉴텍', 'Hack Squat Machine (NT-07L)', '뉴텍 핵 스쿼트 머신', 'quads'),
    ('뉴텍', 'Seated Chest Press (NT-08U)', '뉴텍 시티드 체스트 프레스', 'chest'),
    ('뉴텍', 'Pec Deck Fly / Reverse (NT-09U)', '뉴텍 펙덱 플라이', 'chest'),
    ('뉴텍', 'Glute Machine (NT-09L)', '뉴텍 글루트 머신', 'glutes'),
    ('뉴텍', 'Hammer Shoulder Bench', '뉴텍 해머 숄더 벤치', 'shoulders'),
    ('뉴텍', 'Preacher Curl Bench (Stand)', '뉴텍 프리처 컬 벤치', 'biceps'),
    ('뉴텍', 'Arm Curl Machine (NT-10U)', '뉴텍 암 컬 머신', 'biceps'),
    ('뉴텍', 'Shoulder Press (NT-11U)', '뉴텍 숄더 프레스', 'shoulders'),
    ('뉴텍', 'Abdominal Machine (NT-12U)', '뉴텍 업도미널 머신', 'abs'),
    ('뉴텍', 'Rotary Torso (NT-13U)', '뉴텍 로터리 토르소', 'obliques'),
    ('뉴텍', 'Seated Row Machine (NT-14U)', '뉴텍 시티드 로우', 'back'),
    ('뉴텍', 'Long Pull Machine (NT-15U)', '뉴텍 롱 풀', 'back'),
    ('뉴텍', 'High Pulley Machine (NT-16U)', '뉴텍 하이 풀리', 'lats'),
    ('뉴텍', 'Chin & Dip Assist Machine (NT-17U)', '뉴텍 친/딥 어시스트', 'lats'),
    ('뉴텍', 'Smith Machine (NT-18M)', '뉴텍 스미스 머신', None),
    ('뉴텍', 'Lateral Raise Machine (NT-18U)', '뉴텍 래터럴 레이즈', 'side_delt'),
    ('뉴텍', 'Cable Crossover Machine (NT-19M)', '뉴텍 케이블 크로스오버', 'chest'),
    ('뉴텍', 'Incline Chest Press Machine (NT-19U)', '뉴텍 인클라인 체스트 프레스', 'upper_chest'),
    ('뉴텍', 'Dual Pulley Machine (NT-20M)', '뉴텍 듀얼 풀리', None),
    ('뉴텍', 'Hack Squat (NT-20L)', '뉴텍 핵 스쿼트', 'quads'),
    ('뉴텍', 'Half Rack (NT-22F)', '뉴텍 하프 랙', None),
    ('뉴텍', 'Dual Pulley Pro (C-DPP)', '뉴텍 듀얼 풀리 프로', None),
    ('뉴텍', 'Hip Adduction/Abduction Combo (A-ADD/ABD)', '뉴텍 힙 어덕션/어브덕션', 'adductors'),
    ('뉴텍', 'Seated Dip (A-SD)', '뉴텍 시티드 딥', 'triceps'),
    ('뉴텍', 'Hammer Flat Bench Press (NT-01F)', '뉴텍 해머 플랫 벤치 프레스', 'chest'),
    ('뉴텍', 'Hammer Decline Bench Press (NT-02F)', '뉴텍 해머 디클라인 벤치 프레스', 'lower_chest'),
    ('뉴텍', 'Hammer Incline Bench Press (NT-03F)', '뉴텍 해머 인클라인 벤치 프레스', 'upper_chest'),
    ('뉴텍', 'Dip & Leg Raise (NT-04F)', '뉴텍 딥/레그 레이즈', 'abs'),
    ('뉴텍', 'Sit-up Board (NT-05F)', '뉴텍 싯업 보드', 'abs'),
    ('뉴텍', 'Roman Chair (NT-06F)', '뉴텍 로만 체어', 'lower_back'),
    ('뉴텍', '2-Person Twist (NT-07F)', '뉴텍 트위스트', 'obliques'),
    ('뉴텍', 'Olympic Bench Press (NT-10F)', '뉴텍 올림픽 벤치 프레스', 'chest'),
    ('뉴텍', 'Olympic Incline Bench Press (NT-11F)', '뉴텍 올림픽 인클라인 벤치', 'upper_chest'),
    ('뉴텍', 'Olympic Decline Bench Press (NT-12F)', '뉴텍 올림픽 디클라인 벤치', 'lower_chest'),
    ('뉴텍', 'Preacher Curl (NT-13F)', '뉴텍 프리처 컬', 'biceps'),
    ('뉴텍', 'Power Rack (NT-14F)', '뉴텍 파워 랙', None),
    ('뉴텍', 'Squat Rack (NT-15F)', '뉴텍 스쿼트 랙', None),
    ('뉴텍', 'Adjustable Bench Press (NT-17F)', '뉴텍 각도조절 벤치', None),
    ('뉴텍', 'Adjustable Decline Bench (NT-18F)', '뉴텍 각도조절 디클라인 벤치', 'abs'),
    ('뉴텍', '90-Degree Roman Chair (NT-19F)', '뉴텍 90도 로만 체어', 'lower_back'),
    ('뉴텍', 'T-Bar Row (NT-20F)', '뉴텍 티바 로우', 'back'),
    ('뉴텍', '3D Smith Machine (3D Rack)', '뉴텍 3D 스미스', None),
    ('뉴텍', 'Seated Calf Raise (NT-23F)', '뉴텍 시티드 카프 레이즈', 'soleus'),
    ('뉴텍', 'Shoulder Assist Bench (NT-25F)', '뉴텍 숄더 벤치', 'shoulders'),
]
