"""§11.2 내장 종목의 보조(협응) 근육 초안 — 간접 볼륨(0.5 세트) 후보.

규칙: 종목 기본 타겟은 넣지 않는다 (같은 근육이면 VIEW가 제외). 코드는 targets.py의 것만,
최대 3개. RP식 "간접 세트" 관례 기준 (프레스→삼두·전면삼각, 로우/풀다운→이두, 스쿼트→둔근 …).
데이터 파일 — 사용자가 검토·수정한다. v5 마이그레이션이 한 번 채우고, 이후 새 내장 종목은
INSERT 시점에 함께 들어간다. 이미 채워진 행은 앱(관리자)에서 고친다.
"""

# name_ko -> 보조 근육 코드 튜플 (0~3개, 기본 타겟 제외)
SECONDARY = {
    # ---- 가슴 프레스 계열 ----
    "벤치프레스": ("triceps", "front_delt"),
    "인클라인 벤치프레스": ("triceps", "front_delt"),
    "디클라인 벤치프레스": ("triceps", "front_delt"),
    "클로즈 그립 벤치프레스": ("chest", "front_delt"),
    "와이드 그립 벤치프레스": ("triceps", "front_delt"),
    "리버스 그립 벤치프레스": ("triceps", "front_delt"),
    "스미스머신 벤치프레스": ("triceps", "front_delt"),
    "인클라인 스미스머신 프레스": ("triceps", "front_delt"),
    "디클라인 스미스머신 프레스": ("triceps", "front_delt"),
    "덤벨 벤치프레스": ("triceps", "front_delt"),
    "인클라인 덤벨프레스": ("triceps", "front_delt"),
    "디클라인 덤벨프레스": ("triceps", "front_delt"),
    "뉴트럴 그립 덤벨프레스": ("triceps", "front_delt"),
    "원암 덤벨 벤치프레스": ("triceps", "front_delt"),
    "덤벨 스퀴즈 프레스": ("triceps", "front_delt"),
    "플로어 프레스": ("triceps", "front_delt"),
    "덤벨 플로어 프레스": ("triceps", "front_delt"),
    "체스트 프레스 머신": ("triceps", "front_delt"),
    "인클라인 프레스 머신": ("triceps", "front_delt"),
    "시티드 인클라인 체스트 프레스 머신": ("triceps", "front_delt"),
    "디클라인 프레스 머신": ("triceps", "front_delt"),
    "플레이트 로디드 체스트 프레스": ("triceps", "front_delt"),
    "케이블 체스트 프레스": ("triceps", "front_delt"),
    "스벤드 프레스": (),
    "딥스": ("triceps", "front_delt"),
    "웨이티드 딥스": ("triceps", "front_delt"),
    "어시스티드 딥스": ("triceps", "front_delt"),
    "머신 딥스": ("chest", "front_delt"),
    "푸시업": ("triceps", "front_delt"),
    "웨이티드 푸시업": ("triceps", "front_delt"),
    "인클라인 푸시업": ("triceps", "front_delt"),
    "디클라인 푸시업": ("triceps", "front_delt"),
    "다이아몬드 푸시업": ("chest", "front_delt"),
    "와이드 푸시업": ("triceps", "front_delt"),
    "아처 푸시업": ("triceps", "front_delt"),
    # ---- 플라이 / 크로스오버 (고립) ----
    "덤벨 플라이": (),
    "인클라인 덤벨 플라이": (),
    "디클라인 덤벨 플라이": (),
    "펙덱 플라이": (),
    "케이블 플라이": (),
    "인클라인 케이블 플라이": (),
    "시티드 케이블 플라이": (),
    "원암 케이블 플라이": (),
    "케이블 크로스오버": (),
    "하이 케이블 크로스오버": (),
    "로우 케이블 크로스오버": (),
    # ---- 풀오버 ----
    "덤벨 풀오버": ("lats", "triceps"),
    "바벨 풀오버": ("lats", "triceps"),
    "머신 풀오버": ("chest", "triceps"),
    "케이블 풀오버": ("chest", "triceps"),
    # ---- 데드리프트 / 힙 힌지 ----
    "데드리프트": ("hamstrings", "erector_spinae", "quads"),
    "스모 데드리프트": ("quads", "adductors", "erector_spinae"),
    "루마니안 데드리프트": ("glutes", "erector_spinae"),
    "덤벨 루마니안 데드리프트": ("glutes", "erector_spinae"),
    "싱글레그 루마니안 데드리프트": ("glutes", "erector_spinae"),
    "스티프레그 데드리프트": ("glutes", "erector_spinae"),
    "덤벨 스티프레그 데드리프트": ("glutes", "erector_spinae"),
    "스미스머신 루마니안 데드리프트": ("glutes", "erector_spinae"),
    "트랩바 데드리프트": ("quads", "hamstrings", "erector_spinae"),
    "데피싯 데드리프트": ("hamstrings", "erector_spinae", "quads"),
    "스내치 그립 데드리프트": ("glutes", "hamstrings", "erector_spinae"),
    "랙풀": ("glutes", "hamstrings", "upper_traps"),
    "케틀벨 데드리프트": ("hamstrings", "quads", "erector_spinae"),
    "굿모닝": ("glutes", "erector_spinae"),
    "시티드 굿모닝": ("hamstrings", "glutes"),
    # ---- 로우 ----
    "바벨 로우": ("biceps", "rear_delt"),
    "언더핸드 바벨 로우": ("biceps", "rear_delt"),
    "펜들레이 로우": ("biceps", "rear_delt"),
    "티바 로우": ("biceps", "rear_delt"),
    "체스트 서포티드 티바 로우 머신": ("biceps", "rear_delt"),
    "미도우 로우": ("biceps", "rear_delt"),
    "원암 덤벨 로우": ("biceps", "rear_delt"),
    "덤벨 벤트오버 로우": ("biceps", "rear_delt"),
    "체스트 서포티드 덤벨 로우": ("biceps", "rear_delt"),
    "크록 로우": ("biceps", "rear_delt", "forearms"),
    "케틀벨 로우": ("biceps", "rear_delt"),
    "시티드 케이블 로우": ("biceps", "rear_delt"),
    "와이드 그립 시티드 케이블 로우": ("biceps", "rear_delt"),
    "언더핸드 시티드 케이블 로우": ("biceps", "rear_delt"),
    "로프 시티드 케이블 로우": ("biceps", "rear_delt"),
    "원암 케이블 로우": ("biceps", "rear_delt"),
    "스탠딩 케이블 로우": ("biceps", "rear_delt"),
    "하이 로우": ("biceps", "rear_delt"),
    "로우 로우": ("biceps", "rear_delt"),
    "시티드 로우 머신": ("biceps", "rear_delt"),
    "아이소 래터럴 로우": ("biceps", "rear_delt"),
    "원암 머신 로우": ("biceps", "rear_delt"),
    "스미스머신 로우": ("biceps", "rear_delt"),
    "인버티드 로우": ("biceps", "rear_delt"),
    "TRX 로우": ("biceps", "rear_delt"),
    "밴드 로우": ("biceps", "rear_delt"),
    "리어델트 로우": ("mid_traps", "biceps"),
    # ---- 풀업 / 풀다운 ----
    "풀업": ("biceps",),
    "친업": ("biceps",),
    "와이드 그립 풀업": ("biceps",),
    "클로즈 그립 풀업": ("biceps",),
    "뉴트럴 그립 풀업": ("biceps",),
    "웨이티드 풀업": ("biceps",),
    "웨이티드 친업": ("biceps",),
    "어시스티드 풀업": ("biceps",),
    "밴드 풀업": ("biceps",),
    "랫풀다운": ("biceps",),
    "클로즈 그립 랫풀다운": ("biceps",),
    "언더핸드 랫풀다운": ("biceps",),
    "뉴트럴 그립 랫풀다운": ("biceps",),
    "비하인드 넥 랫풀다운": ("biceps",),
    "원암 랫풀다운": ("biceps",),
    "니링 랫풀다운": ("biceps",),
    "로프 랫풀다운": ("biceps",),
    "머신 풀다운": ("biceps",),
    "스트레이트 암 풀다운": ("chest", "triceps"),
    # ---- 슈러그 (고립) ----
    "슈러그": (),
    "덤벨 슈러그": (),
    "스미스머신 슈러그": (),
    "트랩바 슈러그": (),
    "케이블 슈러그": (),
    "머신 슈러그": (),
    "비하인드 백 슈러그": (),
    "인클라인 덤벨 슈러그": (),
    # ---- 백 익스텐션 / 허리 ----
    "백 익스텐션": ("glutes", "hamstrings"),
    "45도 백 익스텐션": ("glutes", "hamstrings"),
    "웨이티드 백 익스텐션": ("glutes", "hamstrings"),
    "글루트 포커스 백 익스텐션": ("hamstrings", "erector_spinae"),
    "백 익스텐션 머신": ("glutes", "hamstrings"),
    "리버스 하이퍼익스텐션": ("hamstrings", "erector_spinae"),
    "슈퍼맨": ("glutes",),
    "제퍼슨 컬": ("hamstrings",),
    "버드독": ("glutes",),
    # ---- 숄더프레스 ----
    "오버헤드 프레스": ("triceps", "upper_traps"),
    "시티드 바벨 숄더프레스": ("triceps", "upper_traps"),
    "비하인드 넥 프레스": ("triceps", "upper_traps"),
    "푸시 프레스": ("triceps", "upper_traps", "quads"),
    "Z 프레스": ("triceps", "upper_traps"),
    "덤벨 숄더프레스": ("triceps", "upper_traps"),
    "스탠딩 덤벨 숄더프레스": ("triceps", "upper_traps"),
    "아놀드 프레스": ("triceps", "upper_traps"),
    "원암 덤벨 숄더프레스": ("triceps", "upper_traps"),
    "뉴트럴 그립 덤벨 숄더프레스": ("triceps", "upper_traps"),
    "숄더 프레스 머신": ("triceps", "upper_traps"),
    "플레이트 로디드 숄더프레스": ("triceps", "upper_traps"),
    "스미스머신 숄더프레스": ("triceps", "upper_traps"),
    "케이블 숄더프레스": ("triceps", "upper_traps"),
    "케틀벨 프레스": ("triceps", "upper_traps"),
    "랜드마인 프레스": ("triceps", "upper_chest"),
    "파이크 푸시업": ("triceps", "upper_traps"),
    "핸드스탠드 푸시업": ("triceps", "upper_traps"),
    # ---- 레터럴 레이즈 (고립) ----
    "사이드 레터럴 레이즈": (),
    "시티드 레터럴 레이즈": (),
    "원암 덤벨 레터럴 레이즈": (),
    "리닝 레터럴 레이즈": (),
    "인클라인 레터럴 레이즈": (),
    "케이블 레터럴 레이즈": (),
    "비하인드 백 케이블 레터럴 레이즈": (),
    "레터럴 레이즈 머신": (),
    "루 레이즈": ("upper_traps",),
    "밴드 레터럴 레이즈": (),
    # ---- 업라이트 로우 ----
    "업라이트 로우": ("upper_traps", "biceps"),
    "덤벨 업라이트 로우": ("upper_traps", "biceps"),
    "케이블 업라이트 로우": ("upper_traps", "biceps"),
    "스미스머신 업라이트 로우": ("upper_traps", "biceps"),
    # ---- 프론트 레이즈 (고립) ----
    "프론트 레이즈": (),
    "바벨 프론트 레이즈": (),
    "플레이트 프론트 레이즈": (),
    "케이블 프론트 레이즈": (),
    "인클라인 프론트 레이즈": (),
    # ---- 리어델트 / 페이스풀 ----
    "리어델트 플라이": (),
    "시티드 리어델트 플라이": (),
    "인클라인 리어델트 플라이": (),
    "리버스 펙덱 플라이": (),
    "케이블 리어델트 플라이": (),
    "원암 케이블 리어델트 플라이": (),
    "페이스풀": ("mid_traps",),
    "시티드 페이스풀": ("mid_traps",),
    "밴드 페이스풀": ("mid_traps",),
    "밴드 풀어파트": ("mid_traps",),
    "Y 레이즈": ("rear_delt",),
    # ---- 회전근개 (고립) ----
    "케이블 외회전": (),
    "케이블 내회전": (),
    "덤벨 외회전": (),
    "밴드 외회전": (),
    "밴드 내회전": (),
    "쿠반 로테이션": (),
    "스캡션 레이즈": (),
    # ---- 이두 컬 ----
    "바벨 컬": ("forearms",),
    "EZ바 컬": ("forearms",),
    "와이드 그립 바벨 컬": ("forearms",),
    "클로즈 그립 바벨 컬": ("forearms",),
    "드래그 컬": ("forearms",),
    "리버스 컬": ("brachialis",),
    "EZ바 리버스 컬": ("brachialis",),
    "덤벨 리버스 컬": ("brachialis",),
    "케이블 리버스 컬": ("brachialis",),
    "덤벨 컬": ("forearms",),
    "시티드 덤벨 컬": ("forearms",),
    "인클라인 덤벨 컬": ("forearms",),
    "스파이더 컬": ("forearms",),
    "EZ바 스파이더 컬": ("forearms",),
    "컨센트레이션 컬": ("forearms",),
    "해머 컬": ("brachioradialis",),
    "크로스바디 해머 컬": ("brachioradialis",),
    "인클라인 해머 컬": ("brachioradialis",),
    "로프 해머 컬": ("brachioradialis",),
    "조트만 컬": ("biceps",),
    "웨이터 컬": ("forearms",),
    "프리처 컬": ("forearms",),
    "바벨 프리처 컬": ("forearms",),
    "덤벨 프리처 컬": ("forearms",),
    "케이블 프리처 컬": ("forearms",),
    "이두 컬 머신": ("forearms",),
    "케이블 컬": ("forearms",),
    "원암 케이블 컬": ("forearms",),
    "하이 케이블 컬": ("forearms",),
    "베이지안 컬": ("forearms",),
    "라잉 케이블 컬": ("forearms",),
    "밴드 컬": ("forearms",),
    # ---- 삼두 ----
    "케이블 푸시다운": (),
    "로프 푸시다운": (),
    "V바 푸시다운": (),
    "리버스 그립 푸시다운": (),
    "원암 케이블 푸시다운": (),
    "원암 리버스 그립 푸시다운": (),
    "라잉 트라이셉스 익스텐션": (),
    "덤벨 라잉 트라이셉스 익스텐션": (),
    "인클라인 라잉 트라이셉스 익스텐션": (),
    "오버헤드 트라이셉스 익스텐션": (),
    "원암 오버헤드 덤벨 익스텐션": (),
    "EZ바 오버헤드 트라이셉스 익스텐션": (),
    "케이블 오버헤드 트라이셉스 익스텐션": (),
    "케이블 트라이셉스 익스텐션": (),
    "라잉 케이블 트라이셉스 익스텐션": (),
    "트라이셉스 익스텐션 머신": (),
    "덤벨 킥백": (),
    "케이블 트라이셉스 킥백": (),
    "JM 프레스": ("chest", "front_delt"),
    "테이트 프레스": (),
    "벤치 딥스": ("front_delt", "chest"),
    "스미스머신 클로즈 그립 벤치프레스": ("chest", "front_delt"),
    "덤벨 클로즈 그립 프레스": ("chest", "front_delt"),
    "밴드 푸시다운": (),
    # ---- 전완 (고립) ----
    "리스트 컬": (),
    "덤벨 리스트 컬": (),
    "케이블 리스트 컬": (),
    "비하인드 백 리스트 컬": (),
    "리버스 리스트 컬": (),
    "덤벨 리버스 리스트 컬": (),
    "리스트 롤러": (),
    "플레이트 핀치 컬": (),
    "덤벨 프로네이션 수피네이션": (),
    # ---- 스쿼트 ----
    "백스쿼트": ("glutes", "adductors"),
    "로우바 스쿼트": ("glutes", "erector_spinae", "adductors"),
    "프론트 스쿼트": ("glutes", "adductors"),
    "박스 스쿼트": ("glutes", "adductors"),
    "포즈 스쿼트": ("glutes", "adductors"),
    "세이프티바 스쿼트": ("glutes", "erector_spinae", "adductors"),
    "제르처 스쿼트": ("glutes", "erector_spinae", "adductors"),
    "오버헤드 스쿼트": ("glutes", "adductors"),
    "랜드마인 스쿼트": ("glutes", "adductors"),
    "고블릿 스쿼트": ("glutes", "adductors"),
    "덤벨 스쿼트": ("glutes", "adductors"),
    "스모 스쿼트": ("quads", "glutes"),
    "스미스머신 스쿼트": ("glutes", "adductors"),
    "스미스머신 프론트 스쿼트": ("glutes", "adductors"),
    "맨몸 스쿼트": ("glutes", "adductors"),
    "점프 스쿼트": ("glutes", "calves", "adductors"),
    "피스톨 스쿼트": ("glutes", "adductors"),
    "스패니시 스쿼트": (),
    "시시 스쿼트": (),
    "핵 스쿼트": ("glutes", "adductors"),
    "리버스 핵 스쿼트": ("quads", "hamstrings", "adductors"),
    "바벨 핵 스쿼트": ("glutes", "adductors"),
    "펜듈럼 스쿼트": ("glutes", "adductors"),
    "V 스쿼트": ("glutes", "adductors"),
    "벨트 스쿼트": ("glutes", "adductors"),
    # ---- 레그 프레스 ----
    "레그 프레스": ("glutes",),
    "수평 레그 프레스": ("glutes",),
    "버티컬 레그 프레스": ("glutes",),
    "싱글레그 레그 프레스": ("glutes",),
    "와이드 스탠스 레그 프레스": ("quads", "glutes"),
    "내로우 스탠스 레그 프레스": ("glutes",),
    "하이풋 레그 프레스": ("hamstrings", "quads"),
    # ---- 레그 익스텐션 (고립) ----
    "레그 익스텐션": (),
    "싱글레그 레그 익스텐션": (),
    "리버스 노르딕 컬": (),
    # ---- 런지 / 스플릿 스쿼트 / 스텝업 ----
    "런지": ("glutes",),
    "바벨 런지": ("glutes",),
    "워킹 런지": ("quads", "hamstrings"),
    "바벨 워킹 런지": ("quads", "hamstrings"),
    "리버스 런지": ("quads", "hamstrings"),
    "바벨 리버스 런지": ("quads", "hamstrings"),
    "스미스머신 런지": ("glutes",),
    "사이드 런지": ("quads", "glutes"),
    "커치 런지": ("quads", "adductors"),
    "맨몸 런지": ("glutes",),
    "스플릿 스쿼트": ("glutes",),
    "불가리안 스플릿 스쿼트": ("glutes",),
    "바벨 불가리안 스플릿 스쿼트": ("glutes",),
    "스미스머신 불가리안 스플릿 스쿼트": ("glutes",),
    "스텝업": ("glutes",),
    "바벨 스텝업": ("glutes",),
    "맨몸 스텝업": ("glutes",),
    # ---- 레그 컬 ----
    "레그 컬": (),
    "시티드 레그 컬": (),
    "스탠딩 레그 컬": (),
    "싱글레그 라잉 레그 컬": (),
    "케이블 레그 컬": (),
    "덤벨 레그 컬": (),
    "슬라이더 레그 컬": ("glutes",),
    "스위스볼 레그 컬": ("glutes",),
    "노르딕 컬": (),
    "글루트 햄 레이즈": ("glutes", "calves"),
    # ---- 둔근 ----
    "케틀벨 스윙": ("hamstrings", "erector_spinae"),
    "힙 쓰러스트": ("hamstrings",),
    "힙 쓰러스트 머신": ("hamstrings",),
    "스미스머신 힙 쓰러스트": ("hamstrings",),
    "덤벨 힙 쓰러스트": ("hamstrings",),
    "싱글레그 힙 쓰러스트": ("hamstrings",),
    "밴드 힙 쓰러스트": ("hamstrings",),
    "글루트 브릿지": ("hamstrings",),
    "바벨 글루트 브릿지": ("hamstrings",),
    "싱글레그 글루트 브릿지": ("hamstrings",),
    "프로그 펌프": (),
    "케이블 글루트 킥백": ("hamstrings",),
    "글루트 킥백 머신": ("hamstrings",),
    "덩키 킥": ("hamstrings",),
    "파이어 하이드런트": (),
    "케이블 풀스루": ("hamstrings", "erector_spinae"),
    "힙 어브덕션 머신": (),
    "케이블 힙 어브덕션": (),
    "사이드 라잉 힙 어브덕션": (),
    "밴드 어브덕션": (),
    "클램쉘": (),
    "힙 어덕션 머신": (),
    "케이블 힙 어덕션": (),
    "코펜하겐 어덕션": (),
    # ---- 종아리 (고립) ----
    "스탠딩 카프 레이즈": (),
    "시티드 카프 레이즈": (),
    "레그 프레스 카프 레이즈": (),
    "핵 스쿼트 카프 레이즈": (),
    "스미스머신 카프 레이즈": (),
    "바벨 카프 레이즈": (),
    "덤벨 카프 레이즈": (),
    "싱글레그 카프 레이즈": (),
    "맨몸 카프 레이즈": (),
    "동키 카프 레이즈": (),
    "시티드 덤벨 카프 레이즈": (),
    "티비아 레이즈": (),
    # ---- 코어 ----
    "크런치": (),
    "케이블 크런치": (),
    "크런치 머신": (),
    "디클라인 크런치": (),
    "웨이티드 크런치": (),
    "리버스 크런치": ("hip_flexors",),
    "바이시클 크런치": ("hip_flexors",),
    "오블리크 크런치": (),
    "싯업": ("hip_flexors",),
    "디클라인 싯업": ("hip_flexors",),
    "웨이티드 싯업": ("hip_flexors",),
    "V업": ("hip_flexors",),
    "행잉 레그 레이즈": ("hip_flexors",),
    "행잉 니 레이즈": ("hip_flexors",),
    "토즈 투 바": ("hip_flexors",),
    "캡틴스 체어 레그 레이즈": ("hip_flexors",),
    "라잉 레그 레이즈": ("hip_flexors",),
    "드래곤 플래그": ("hip_flexors",),
    "앱 롤아웃": ("hip_flexors", "lats"),
    "바벨 롤아웃": ("hip_flexors", "lats"),
    "스탠딩 앱 롤아웃": ("hip_flexors", "lats"),
    "러시안 트위스트": (),
    "케이블 우드촙": (),
    "로우 투 하이 케이블 우드촙": (),
    "팔로프 프레스": (),
    "사이드 밴드": ("quadratus_lumborum",),
    "케이블 사이드 밴드": ("quadratus_lumborum",),
    "로터리 토르소 머신": (),
    "데드 버그": ("hip_flexors",),
    "케이블 힙 플렉션": (),
    "시티드 니 업": ("abs",),
    "밴드 힙 플렉션": (),
    "스탠딩 니 레이즈": (),
    # ---- 역도 / 전신 ----
    "파워 클린": ("quads", "hamstrings", "upper_traps"),
    "행 클린": ("quads", "hamstrings", "upper_traps"),
    "클린 앤 저크": ("quads", "upper_traps", "front_delt"),
    "파워 스내치": ("quads", "hamstrings", "upper_traps"),
    "행 스내치": ("quads", "hamstrings", "upper_traps"),
    "하이 풀": ("glutes", "hamstrings", "quads"),
    "스러스터": ("glutes", "front_delt", "triceps"),
    "덤벨 스러스터": ("glutes", "front_delt", "triceps"),
    "터키시 겟업": ("abs", "glutes"),
    "케틀벨 클린": ("hamstrings", "erector_spinae"),
    "케틀벨 스내치": ("hamstrings", "erector_spinae", "shoulders"),
    "버피": ("glutes", "chest", "triceps"),
}
